### ISSUE TITLE
'Launch' typo & Auto-launch bug

### ISSUE THREAD

**Issue by glasgowm148** [2ndtlmining/ergotx#6]
Should be Launch

![image](https://github.com/user-attachments/assets/d71812dc-4c0a-45b4-8e57-3be9e42ecdbe)

Also if you click 'Auto-launch' you can't get to the block visualiser.

**Comment by 2ndtlmining** [comment]
hey @glasgowm148 

I feel honored. Thanks for helping. Fixed the issue and merged the code, will push the update to the front end.
The auto launch toggle, will save to cookies that you want to go to tx page. But with this update you can still go `/blocks`

![image](https://github.com/user-attachments/assets/34f5f071-94c7-4c96-a212-f37093ca1f61)


/blocks

![image](https://github.com/user-attachments/assets/3bb85040-3207-42c4-a400-2253ba465e42)
